name: Deploy Development

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-dev
  cancel-in-progress: false

env:
  AWS_REGION: eu-west-3
  ECR_REPOSITORY: aws-cicd-platform-app
  ECS_CLUSTER: aws-cicd-platform-dev-cluster
  ECS_SERVICE: aws-cicd-platform-dev-service
  CONTAINER_NAME: app
  ALB_NAME: aws-cicd-platform-dev-alb

jobs:
  deploy:
    name: Build, scan and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display OIDC repository context
        run: |
            echo "repository=${GITHUB_REPOSITORY}"
            echo "repository_owner_id=${GITHUB_REPOSITORY_OWNER_ID}"
            echo "repository_id=${GITHUB_REPOSITORY_ID}"

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Authenticate Docker to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI="${REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

          docker build \
            --pull \
            --no-cache \
            -f app/Dockerfile \
            -t "${IMAGE_URI}" \
            app

          echo "IMAGE_URI=${IMAGE_URI}" >> "${GITHUB_ENV}"

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ env.IMAGE_URI }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push image
        run: |
          docker push "${IMAGE_URI}"

      - name: Register ECS task definition
        id: task-definition
        run: |
          aws ecs describe-task-definition \
            --task-definition "aws-cicd-platform-dev-task"
            --region "${AWS_REGION}" \
            --query taskDefinition \
            --output json > task-definition.json

          jq --arg IMAGE "${IMAGE_URI}" '
            .containerDefinitions |= map(
                if .name == "app"
                then .image = $IMAGE
                else .
                end
            )
            | del(
                .taskDefinitionArn,
                .revision,
                .status,
                .requiresAttributes,
                .compatibilities,
                .registeredAt,
                .registeredBy
                )
            ' task-definition.json > task-definition-rendered.json

          TASK_DEFINITION_ARN="$(
            aws ecs register-task-definition \
              --cli-input-json file://task-definition-rendered.json \
              --region "${AWS_REGION}" \
              --query 'taskDefinition.taskDefinitionArn' \
              --output text
          )"

          echo "TASK_DEFINITION_ARN=${TASK_DEFINITION_ARN}" >> "${GITHUB_ENV}"

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster "${ECS_CLUSTER}" \
            --service "${ECS_SERVICE}" \
            --task-definition "${TASK_DEFINITION_ARN}" \
            --force-new-deployment \
            --region "${AWS_REGION}"

      - name: Wait for ECS stability
        run: |
          aws ecs wait services-stable \
            --cluster "${ECS_CLUSTER}" \
            --services "${ECS_SERVICE}" \
            --region "${AWS_REGION}"

      - name: Smoke test
        run: |
          ALB_DNS="$(
            aws elbv2 describe-load-balancers \
              --names "${ALB_NAME}" \
              --region "${AWS_REGION}" \
              --query 'LoadBalancers[0].DNSName' \
              --output text
          )"

          URL="http://${ALB_DNS}/health"

          for attempt in $(seq 1 12); do
            if curl --fail --silent --show-error --max-time 10 "${URL}"; then
              echo
              echo "Smoke test passed."
              exit 0
            fi

            echo "Smoke test attempt ${attempt}/12 failed. Retrying..."
            sleep 10
          done

          echo "Smoke test failed."
          exit 1